CREATE TABLE CART_COUPON (
CART_ID INTEGER NOT NULL,
COUPON_ID INTEGER NOT NULL,
QUANTIY INTEGER NOT NULL,
UNITPrice DECIMAL(10,2) NULL,
DISCOUNTEDPrice DECIMAL(10,2) NULL,
TOTAL_COST DECIMAL(10,2) NOT NULL,
CONSTRAINT CART_PK PRIMARY KEY (CART_ID),
CONSTRAINT COUPON_FK FOREIGN KEY (COUPON_ID) REFERENCES COUPON
)
go