CREATE TABLE COUPON_REVIEW (
REVIEW_ID INTEGER NOT NULL,
COUPON_ID INTEGER NOT NULL,
CUSTOMER_ID INTEGER NOT NULL,
RATING INTEGER NOT NULL,
REVIEW VARCHAR (255) NOT NULL,
CONSTRAINT COUPN_REVIEW_PK PRIMARY KEY (REVIEW_ID)
CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER,
CONSTRAINT COUPON_FK FOREIGN KEY (COUPON_ID) REFERENCES COUPON
) go