CREATE TABLE CouponCategory (
COUPON_ID INTEGER NOT NULL,
CATEGORY_ID INTEGER NOT NULL,
CONSTRAINT COUPON_FK FOREIGN KEY (COUPON_ID) REFERENCES COUPON
CONSTRAINT CATEGORY_PK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY)
go