CREATE TABLE COUPON (
COUPON_ID INTEGER NOT NULL,
COUPON_NAME VARCHAR(50) NOT NULL,
COUPON_DESC VARCHAR(100) NOT NULL,
COUPON_TYPE CHAR(50) NOT NULL,
COUPON_CATEGORY VARCHAR(30) NOT NULL,
COUPON_BEGINDATE DATETIME NULL,
COUPON_EXPIRYTIME DATETIME NULL,
COUPON_ORIGNAL_PRICE DECIMAL(10,2) NOT NULL,
COUPON_DISCOUNT_PRICE DECIMAL(10,2) NOT NULL,
MERCHANT_ID INTEGER NOT NULL,
CONSTRAINT COUPON_PK PRIMARY KEY (COUPON_ID),
CONSTRAINT MERCHANT_FK FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANT
) go