CREATE TABLE CustomerCoupon (
COUPON_ID INTEGER NOT NULL,
CUSTOMER_ID INTEGER NOT NULL,
CONSTRAINT COUPON_FK FOREIGN KEY (COUPON_ID) REFERENCES COUPON
CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER
)
Go