CREATE TABLE CustomerInterest (
CATEGORY_ID INTEGER NOT NULL,
CUSTOMER_ID INTEGER NOT NULL,
CONSTRAINT CATEGORY_PK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY
CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER
)
Go