CREATE TABLE MEMBERSHIP
(
MEMBERSHIP_ID INTEGER NOT NULL
CUSTOMER_ID INTEGER NOT NULL,
Start_DATE DATETIME NOT NULL,
END_DATE DATETIME NOT NULL,
8 | P a g e
MERCHANT_ID INTEGER NOT NULL
CONSTRAINT MEMBERSHIP_PK PRIMARY KEY(MMEMBERSHIP_ID),
CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER,
CONSTRAINT MERCHANT_FK FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANT
) go