CREATE TABLE MERCHANT (
MERCHANT_ID CHAR(11) NOT NULL,
MERCHANT_NAME VARCHAR(30) NOT NULL,
MERCHANT_TYPE CHAR(30) NOT NULL,
Store_NAME VARCHAR(30) NOT NULL,
MERCHANT_ADDRESS VARCHAR(100) NOT NULL,
MERCHANT_CITY VARCHAR(30) NOT NULL,
MERCHANT_STATE VARCHAR(30) NOT NULL,
MERCHANT_ZIP INTEGER NOT NULL,
CONSTRAINT MERCHANT_PK PRIMARY KEY (MERCHANT_ID)
)
go